<?php
// Include the autoloader generated by Composer
require 'vendor/autoload.php';
use Dompdf\Dompdf;
use Dompdf\Options;

// Start session to store the PDF URL temporarily
session_start(); 

// Include your database connection
include 'db.php'; 

// --- Configuration ---
$pdf_dir = 'reports/'; 
// Ensure the reports directory exists and is writable (permission 0777 is common for testing)
if (!is_dir($pdf_dir)) {
    mkdir($pdf_dir, 0777, true); 
}

// --- 1. Fetch Stock Data (Customize this query for your 'inventory' table) ---
$stock_data = [];
$stock_sql = "SELECT product_name, stock_level, reorder_point, supplier FROM inventory ORDER BY product_name ASC";
$stock_res = $conn->query($stock_sql);

if ($stock_res) {
    while($row = $stock_res->fetch_assoc()){
        $stock_data[] = $row;
    }
}
$conn->close();

// --- 2. Generate HTML Content for PDF ---
$html = '<html><head><style>
body { font-family: Arial, sans-serif; }
h1 { color: #34495e; text-align: center; }
table { width: 100%; border-collapse: collapse; margin-top: 20px; }
th, td { border: 1px solid #ddd; padding: 10px; text-align: left; font-size: 12px; }
th { background-color: #f2f2f2; color: #333; }
.report-meta { font-size: 10px; color: #777; text-align: right; }
</style></head><body>';

$html .= '<h1>SCM Pro Stock Inventory Report</h1>';
$html .= '<div class="report-meta">Generated: ' . date('Y-m-d H:i:s') . '</div>';

$html .= '<table><thead><tr>
    <th>Product Name</th>
    <th>Stock Level</th>
    <th>Reorder Point</th>
    <th>Supplier</th>
</tr></thead><tbody>';

if (empty($stock_data)) {
    $html .= '<tr><td colspan="4" style="text-align:center;">No active inventory data found.</td></tr>';
} else {
    foreach ($stock_data as $item) {
        $html .= '<tr>';
        $html .= '<td>' . htmlspecialchars($item['product_name']) . '</td>';
        $html .= '<td>' . number_format($item['stock_level']) . '</td>';
        $html .= '<td>' . number_format($item['reorder_point']) . '</td>';
        $html .= '<td>' . htmlspecialchars($item['supplier']) . '</td>';
        $html .= '</tr>';
    }
}

$html .= '</tbody></table></body></html>';


// --- 3. Configure and Generate PDF ---
$options = new Options();
$options->set('isHtml5ParserEnabled', true);
// Set this if you use external assets like Google Fonts or remote images (recommended)
$options->set('isRemoteEnabled', true); 

$dompdf = new Dompdf($options);
$dompdf->loadHtml($html);
$dompdf->setPaper('A4', 'portrait');
$dompdf->render();

// --- 4. Save the PDF File and prepare the URL ---
$filename = 'Stock_Report_' . time() . '.pdf';
$filepath = $pdf_dir . $filename;

// Write the PDF content to the 'reports/' directory
file_put_contents($filepath, $dompdf->output());

// IMPORTANT: CHANGE THIS BASE URL TO YOUR ACTUAL DOMAIN/PROJECT PATH!
// Example for XAMPP: http://localhost/myprojectname/
$base_url = "http://localhost/scm_system/"; 
$pdf_public_url = $base_url . $filepath;

// Store the public URL in a session variable
$_SESSION['pdf_to_share_url'] = $pdf_public_url;

// Use a separate session message to trigger the successful alert box
$_SESSION['alerts_success_message'] = '<i class="fas fa-file-pdf"></i> **Success!** Inventory Report generated and saved.';

// Redirect back to the main alerts page to show the share button
header("Location: alerts.php");
exit;
?>